// Generated by gencpp from file ex0/AddTwoInts.msg
// DO NOT EDIT!


#ifndef EX0_MESSAGE_ADDTWOINTS_H
#define EX0_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <ex0/AddTwoIntsRequest.h>
#include <ex0/AddTwoIntsResponse.h>


namespace ex0
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace ex0


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ex0::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::ex0::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::ex0::AddTwoInts > {
  static const char* value()
  {
    return "ex0/AddTwoInts";
  }

  static const char* value(const ::ex0::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::ex0::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::ex0::AddTwoInts >
template<>
struct MD5Sum< ::ex0::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ex0::AddTwoInts >::value();
  }
  static const char* value(const ::ex0::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ex0::AddTwoIntsRequest> should match
// service_traits::DataType< ::ex0::AddTwoInts >
template<>
struct DataType< ::ex0::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::ex0::AddTwoInts >::value();
  }
  static const char* value(const ::ex0::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ex0::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::ex0::AddTwoInts >
template<>
struct MD5Sum< ::ex0::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ex0::AddTwoInts >::value();
  }
  static const char* value(const ::ex0::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ex0::AddTwoIntsResponse> should match
// service_traits::DataType< ::ex0::AddTwoInts >
template<>
struct DataType< ::ex0::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::ex0::AddTwoInts >::value();
  }
  static const char* value(const ::ex0::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EX0_MESSAGE_ADDTWOINTS_H
